### ISSUE TITLE
Payment 

### ISSUE THREAD

**Issue by olaven** [olaven/krets#118]
## Description 
It should be possible to sign up for a subscription through an integration with Stripe.

## Checklist 
- [X] Understanding how Stripe works - I should follow [this approach](https://stripe.com/docs/billing/subscriptions/metered-billing#reporting-usage), as it allows for a base price + usage cost
- [x] Setup (not implement yet) and understand webhooks - as per #119 
- [x] Configure Stripe products - done in GUI
- [x] Create test-page - as per #123 
- [x] Figure out testing environment (e.g. keys and accounts)
- [x] Figure out how payment flow works - as per #126 -> https://stripe.com/docs/billing/subscriptions/metered
- [X] Database supports customer IDs - as per #128
- [x] Database supports subscription and price IDs - as per #129 
- [x] Collect payment with GUI components -> [step 5](https://stripe.com/docs/billing/subscriptions/metered#collect-payment) - as per #134 
- [x] Persist subscription status in backend - as per #141 
- [x] Must be possible to have a "free-premium"-status as a user (for users helping me out with testing) - as per [this commit](https://github.com/olaven/krets/commit/25cb7b1c0ffdf0615ae5b58e4c25b069f7ff37f9)
- [x] Server updates Stripe User Records based on Krets-usage 
- [x] Handle Stripe webhook events (succeed/failed payment) - as per #143 
- [x] Should be able to upgrade after signup

**Comment by olaven** [comment]
Closing, as basic payment is implemented. 
It is possible to subscribe! 😄
