### ISSUE TITLE
Page providing upgrade options

### ISSUE THREAD

**Issue by olaven** [olaven/krets#139]
Finish the payment GUI started with #118 

## Description 
Page should show available subscription options and the user should 
be able to purchase them. 

## Checklist 
- [x] Get options from Stripe? - as per #142 
- [x] Implement cards - as per #150 
- [x] Test (automatically) - as per #164 
- [x] Test manually in test environment 
- [x] Test manually in production environment

**Comment by olaven** [comment]
Reopening, as extensive testing is missing.
