### ISSUE TITLE
Choose questions

### ISSUE THREAD

**Issue by olaven** [olaven/krets#188]
## Description 
A test user requested a feature that allowed them to specify three custom questions. 
While this breaks somewhat with the initial philosophy of Krets, I think it could be an interesting 
experiment. _As long as_ it is __opt in__, both for the giver and receiver of feedback. 

I see this as a potentially useful future paid feature and, if nothing else, a great experiment!

## Checklist 
- [x] Design - as per #197 
- [x] Plan and update DB-structure - as per #192  
- [x] Implement feature backend - Partly by #192, fully as per #195
- [x] Make it opt-in from settings - as per #197 
- [x] Implement feature when giving feedback - as per #197 
- [x] Figure out how to display in admin page - as per #197 
- [x] Implement admin page display - as per #197

**Comment by olaven** [comment]
Waiting to merge until I have fixed some minor annoyances outlined [here](https://github.com/olaven/krets/pull/197#issuecomment-679327577)

**Comment by olaven** [comment]
Closing, as #197 is finished. 
(should have been linked, my bad)
