### ISSUE TITLE
Subscription Only

### ISSUE THREAD

**Issue by olaven** [olaven/krets#222]
## Description
As documented in #145, the platform should now be subscription only, with a trail. 
This issue tracks the project of that transition. 

## Tracking 
This is a larger issue, with a custom release branch, `subscription-only`. 
This branch is tracked over at #223. 

## Checklist 
- [x] GUI redirects to `/user` if user is not subscribed - as per #224 
- [x] Rename 'upgrade' to 'setup subscription'. Update to more fitting wording overall. - as per #225 
- [x] inform about trail - as per #225
- [x] handling test user access - as per #227
- [x] Make sure test users have a subscription, with __long__ trail  - done in Stripe GUI
- [x] `user.free_premium` should not be needed anymore -> remove it - as per #229
