### ISSUE TITLE
Price Per Page

### ISSUE THREAD

**Issue by olaven** [olaven/krets#235]
Main PR: 

## Description 
The pricing should be as follows: 
- [x] make updates to pricing 
   - [x] Stripe: keep base price roughly the same 
   - [x] Stripe: charge more per page, above some threshold (less for businesses)
   - [x] Stripe: copy prices to production
   - [x] GUI: make sure GUI Reflects the change - as per #237 
- [x] Implement reporting 
    - [x] GitHub Action - as per #239 
    - [x] REST API - as per #238
