### ISSUE TITLE
Improve settings page 

### ISSUE THREAD

**Issue by olaven** [olaven/krets#249]
# Description 
The settings page needs a visual overhaul. If nothing else, the UI/UX should be consistent across the different settings

## Checklist 
- [x] Structure code in a modular way - as per #252 
- [x] Center the content - as per #251 
- [x] Give loading/success feedback mirroring the rest of the platform - as per #260 
- [x] Clearer UI at question creation (some text explaining that something is a question/something is creating a new one) - as per #257

**Comment by olaven** [comment]
Closing, as all tasks are done.
