### ISSUE TITLE
Feedback Embedding 

### ISSUE THREAD

**Issue by olaven** [olaven/krets#262]
## Description
A user should be able to embed the feedback-section on their own page. 
E.g. 
```html
<div id="krets-feedback">
<script src="some_reference">
<script>
    loadKrets("EMBED_KEY_FOR_PAGE");
</script>
</div>
```

To achieve some level of security, a token (generated by the server) has to be provided in the code. 
This is used to check the domain `https://customer-example.com` and the relevant page. The domain is entered by the user when requesting to embed. 

## Checklist
- [X] Sequence Diagram - add to this issue / as per #263
- [x] Implement snippet (without backend, just POC) - as per #266 
- [x] Implement database structure - as per #269 
- [x] Implement API - as per #271 
- [x] Finish snippet (with backend)
- [x] Implement frontend functionality - as per #277 
- [x] remove cors, as it will break email (only token is relevant now) - as per #280 
- [ ] Use on [my website](https://olaven.org) as final full-scale verification 

Diagram -> [here](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtIFxucGFydGljaXBhbnQgUmFuZG9tIFZpc2l0b3JcbnBhcnRpY2lwYW50IEN1c3RvbWVyIFdlYnNpdGVcbnBhcnRpY2lwYW50IEN1c3RvbWVyXG5wYXJ0aWNpcGFudCBGcm9udGVuZCBcbnBhcnRpY2lwYW50IEJhY2tlbmQgXG5wYXJ0aWNpcGFudCBEYXRhYmFzZVxuXG4jIEN1c3RvbWVyIEluaXRpYXRpbmdcbkN1c3RvbWVyIC0-PiBGcm9udGVuZDogSSB3YW50IGVtYmVkLXNuaXBwZXQgZm9yIHRoaXMgcGFnZVxuRnJvbnRlbmQgLS0-PiBDdXN0b21lcjogT3JpZ2luP1xuQ3VzdG9tZXIgLT4-IEZyb250ZW5kOiBcImh0dHBzOi8vZXhhbXBsZS5jb21cIlxuXG4jIEdlbmVyYXRpb24gb2Ygc25pcHBldCAvIHRva2VucyBcbkZyb250ZW5kIC0-PiBCYWNrZW5kOiB7cGFnZV9pZCwgb3JpZ2lufVxuQmFja2VuZCAtPj4gRGF0YWJhc2U6IHN0b3JlIFxuRGF0YWJhc2UgLS0-PiBCYWNrZW5kOiB7cGFnZV9pZCwgb3JpZ2luLCB0b2tlbiwgaWR9XG5CYWNrZW5kIC0-PiBCYWNrZW5kOiBHZW5lcmF0ZSBzbmlwcGV0IGNvZGUgKHdpdGggdG9rZW4pXG5CYWNrZW5kIC0tPj4gRnJvbnRlbmQ6IFRoZSBzbmlwcGV0IGNvZGVcbkZyb250ZW5kIC0-PiBGcm9udGVuZDogRGlzcGxheSBzbmlwcGV0IFxuXG4jIEN1c3RvbWVyIFVzaW5nIFNuaXBwZXQgXG5Gcm9udGVuZCAtPj4gQ3VzdG9tZXI6IENvcHlpbmcgc25pcHBldCBcbkN1c3RvbWVyIC0-PiBDdXN0b21lciBXZWJzaXRlOiBVc2luZyBzbmlwcGV0IFxuXG4jIyBSYW5kb20gdXNlciB1c2luZyBzbmlwcGV0IFxuUmFuZG9tIFZpc2l0b3IgLT4-IEN1c3RvbWVyIFdlYnNpdGU6IEVudGVyaW5nIHJlc3BvbnNlXG5DdXN0b21lciBXZWJzaXRlIC0-PiBCYWNrZW5kOiByZXNwb25zZSArIHRva2VuIFxuQmFja2VuZCAtPj4gIERhdGFiYXNlOiBTbmlwcGV0IGluZm9ybWF0aW9uP1xuRGF0YWJhc2UgLS0-PiBCYWNrZW5kOiBTbmlwcGV0IGluZm9ybWF0aW9uIFxuQmFja2VuZCAtPj4gQmFja2VuZDogQ09SUyBvbiBvcmlnaW4sIHZlcmlmeWluZyBwYWdlPD50b2tlblxuYWx0IEFsbCBjcmVkZW50aWFscyBsb29rIGdvb2QgOi1EXG4gICAgQmFja2VuZCAtPj4gRGF0YWJhc2U6IHBlcnNpc3QgcmVzcG9uc2VcbiAgICBCYWNrZW5kIC0tPj4gQ3VzdG9tZXIgV2Vic2l0ZTogMjAwIE9LXG4gICAgQ3VzdG9tZXIgV2Vic2l0ZSAtLT4-IFJhbmRvbSBWaXNpdG9yOiBUaGFua3MhXG5lbHNlIG5vdCBzbyBnb29kXG4gICAgQmFja2VuZCAtLT4-IEN1c3RvbWVyIFdlYnNpdGU6IDQwMCBCQURfUkVRVUVTVFxuICAgIEN1c3RvbWVyIFdlYnNpdGUgLS0-PiBSYW5kb20gVmlzaXRvcjogQW4gZXJyb3Igb2NjdXJyZWQuLlxuZW5kXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCIsInRoZW1lVmFyaWFibGVzIjp7ImJhY2tncm91bmQiOiJ3aGl0ZSIsInByaW1hcnlDb2xvciI6IiNFQ0VDRkYiLCJzZWNvbmRhcnlDb2xvciI6IiNmZmZmZGUiLCJ0ZXJ0aWFyeUNvbG9yIjoiaHNsKDgwLCAxMDAlLCA5Ni4yNzQ1MDk4MDM5JSkiLCJwcmltYXJ5Qm9yZGVyQ29sb3IiOiJoc2woMjQwLCA2MCUsIDg2LjI3NDUwOTgwMzklKSIsInNlY29uZGFyeUJvcmRlckNvbG9yIjoiaHNsKDYwLCA2MCUsIDgzLjUyOTQxMTc2NDclKSIsInRlcnRpYXJ5Qm9yZGVyQ29sb3IiOiJoc2woODAsIDYwJSwgODYuMjc0NTA5ODAzOSUpIiwicHJpbWFyeVRleHRDb2xvciI6IiMxMzEzMDAiLCJzZWNvbmRhcnlUZXh0Q29sb3IiOiIjMDAwMDIxIiwidGVydGlhcnlUZXh0Q29sb3IiOiJyZ2IoOS41MDAwMDAwMDAxLCA5LjUwMDAwMDAwMDEsIDkuNTAwMDAwMDAwMSkiLCJsaW5lQ29sb3IiOiIjMzMzMzMzIiwidGV4dENvbG9yIjoiIzMzMyIsIm1haW5Ca2ciOiIjRUNFQ0ZGIiwic2Vjb25kQmtnIjoiI2ZmZmZkZSIsImJvcmRlcjEiOiIjOTM3MERCIiwiYm9yZGVyMiI6IiNhYWFhMzMiLCJhcnJvd2hlYWRDb2xvciI6IiMzMzMzMzMiLCJmb250RmFtaWx5IjoiXCJ0cmVidWNoZXQgbXNcIiwgdmVyZGFuYSwgYXJpYWwiLCJmb250U2l6ZSI6IjE2cHgiLCJsYWJlbEJhY2tncm91bmQiOiIjZThlOGU4Iiwibm9kZUJrZyI6IiNFQ0VDRkYiLCJub2RlQm9yZGVyIjoiIzkzNzBEQiIsImNsdXN0ZXJCa2ciOiIjZmZmZmRlIiwiY2x1c3RlckJvcmRlciI6IiNhYWFhMzMiLCJkZWZhdWx0TGlua0NvbG9yIjoiIzMzMzMzMyIsInRpdGxlQ29sb3IiOiIjMzMzIiwiZWRnZUxhYmVsQmFja2dyb3VuZCI6IiNlOGU4ZTgiLCJhY3RvckJvcmRlciI6ImhzbCgyNTkuNjI2MTY4MjI0MywgNTkuNzc2NTM2MzEyOCUsIDg3LjkwMTk2MDc4NDMlKSIsImFjdG9yQmtnIjoiI0VDRUNGRiIsImFjdG9yVGV4dENvbG9yIjoiYmxhY2siLCJhY3RvckxpbmVDb2xvciI6ImdyZXkiLCJzaWduYWxDb2xvciI6IiMzMzMiLCJzaWduYWxUZXh0Q29sb3IiOiIjMzMzIiwibGFiZWxCb3hCa2dDb2xvciI6IiNFQ0VDRkYiLCJsYWJlbEJveEJvcmRlckNvbG9yIjoiaHNsKDI1OS42MjYxNjgyMjQzLCA1OS43NzY1MzYzMTI4JSwgODcuOTAxOTYwNzg0MyUpIiwibGFiZWxUZXh0Q29sb3IiOiJibGFjayIsImxvb3BUZXh0Q29sb3IiOiJibGFjayIsIm5vdGVCb3JkZXJDb2xvciI6IiNhYWFhMzMiLCJub3RlQmtnQ29sb3IiOiIjZmZmNWFkIiwibm90ZVRleHRDb2xvciI6ImJsYWNrIiwiYWN0aXZhdGlvbkJvcmRlckNvbG9yIjoiIzY2NiIsImFjdGl2YXRpb25Ca2dDb2xvciI6IiNmNGY0ZjQiLCJzZXF1ZW5jZU51bWJlckNvbG9yIjoid2hpdGUiLCJzZWN0aW9uQmtnQ29sb3IiOiJyZ2JhKDEwMiwgMTAyLCAyNTUsIDAuNDkpIiwiYWx0U2VjdGlvbkJrZ0NvbG9yIjoid2hpdGUiLCJzZWN0aW9uQmtnQ29sb3IyIjoiI2ZmZjQwMCIsInRhc2tCb3JkZXJDb2xvciI6IiM1MzRmYmMiLCJ0YXNrQmtnQ29sb3IiOiIjOGE5MGRkIiwidGFza1RleHRMaWdodENvbG9yIjoid2hpdGUiLCJ0YXNrVGV4dENvbG9yIjoid2hpdGUiLCJ0YXNrVGV4dERhcmtDb2xvciI6ImJsYWNrIiwidGFza1RleHRPdXRzaWRlQ29sb3IiOiJibGFjayIsInRhc2tUZXh0Q2xpY2thYmxlQ29sb3IiOiIjMDAzMTYzIiwiYWN0aXZlVGFza0JvcmRlckNvbG9yIjoiIzUzNGZiYyIsImFjdGl2ZVRhc2tCa2dDb2xvciI6IiNiZmM3ZmYiLCJncmlkQ29sb3IiOiJsaWdodGdyZXkiLCJkb25lVGFza0JrZ0NvbG9yIjoibGlnaHRncmV5IiwiZG9uZVRhc2tCb3JkZXJDb2xvciI6ImdyZXkiLCJjcml0Qm9yZGVyQ29sb3IiOiIjZmY4ODg4IiwiY3JpdEJrZ0NvbG9yIjoicmVkIiwidG9kYXlMaW5lQ29sb3IiOiJyZWQiLCJsYWJlbENvbG9yIjoiYmxhY2siLCJlcnJvckJrZ0NvbG9yIjoiIzU1MjIyMiIsImVycm9yVGV4dENvbG9yIjoiIzU1MjIyMiIsImNsYXNzVGV4dCI6IiMxMzEzMDAiLCJmaWxsVHlwZTAiOiIjRUNFQ0ZGIiwiZmlsbFR5cGUxIjoiI2ZmZmZkZSIsImZpbGxUeXBlMiI6ImhzbCgzMDQsIDEwMCUsIDk2LjI3NDUwOTgwMzklKSIsImZpbGxUeXBlMyI6ImhzbCgxMjQsIDEwMCUsIDkzLjUyOTQxMTc2NDclKSIsImZpbGxUeXBlNCI6ImhzbCgxNzYsIDEwMCUsIDk2LjI3NDUwOTgwMzklKSIsImZpbGxUeXBlNSI6ImhzbCgtNCwgMTAwJSwgOTMuNTI5NDExNzY0NyUpIiwiZmlsbFR5cGU2IjoiaHNsKDgsIDEwMCUsIDk2LjI3NDUwOTgwMzklKSIsImZpbGxUeXBlNyI6ImhzbCgxODgsIDEwMCUsIDkzLjUyOTQxMTc2NDclKSJ9fX0)

**Comment by olaven** [comment]
This should not have been closed. The code is not in master. 
I remember accidentally merging and reverting locally. Perhaps Github picked that up and closed the issue/PR for me..

**Comment by olaven** [comment]
Feature is pushed as experimental. The real world test is needed. 
That will uncover whether using `iframe` is viable or not.

**Comment by olaven** [comment]
Closing, as want to implement this without iframe in separate issue.
