### ISSUE TITLE
Invoice based B2B

### ISSUE THREAD

**Issue by olaven** [olaven/krets#274]
## Description
Transitioning to manual invoicing 
* pros 
    * allows for individual pricing 
    * easier for a business as they already have a way to handle invoices (and need to file their expenses anyways)
    * established way of doing things 
    * remove Stripe-dependency, which removes a fee as well as complexity
* cons 
    * work scales linearly per customer (can be outsourced/fixed if it actually is a problem, i.e. the business makes money) 

## Checklist 
- [x] Admin page - as per #294 
   - [x] somehow determine admin role  
   - [x] possible to activate/deactivate user 
   - [x] possible to turn other users into admin (double confirmation)
   - [x] make sure that @olaven is admin user on deploy 
- [x] `active`-prop or similar on users in db - as per #290 
- [x] remove Stripe frontend and backend - as per #298 
- [x] Redesign index/signup to indicate this (how about a simple "contact us") - as per #294 
- [X] __IMPORTANT__: remember to give test users `active` status at once after merge.

**Comment by olaven** [comment]
Only missing the complete wipe of Stripe tracked in #298.

**Comment by olaven** [comment]
Closing if deployment turns out well.
