### ISSUE TITLE
redesign of feedback-page

### ISSUE THREAD

**Issue by olaven** [olaven/krets#313]
- [x] [css refresher](https://github.com/vasanthk/css-refresher-notes)
- [x] add stiches to project - as per #314 
- [x] implement 
    - [x]  emoji-changes - as per #316 
    - [x] form-flow - as per #317 
    - [x] emoji transitions - as per #317 
    - [x] form-animations - as per #317

**Comment by olaven** [comment]
Closed, as #315 was merged 🚀
