### ISSUE TITLE
Improve admin page

### ISSUE THREAD

**Issue by olaven** [olaven/krets#87]
## Description 
By default the current bar chart should change to a line graph, with time in the X-axis. 
The bar chart should appear if and only if multiple pages are compared. 
The overall average score should just be shown as a number, as the bar chart does not really add any values when there is only one graph visible. 
Furthermore, improvements should be made to the way text-feedback is displayed. 

## Checklist 
- [x] Show overall score as a number - as per #97 
- [x] Can filter text responses by smiley - as per #86  
- [x] Implement line chart by date - as per #88 
- [x] Just show bar chart when multiple pages are selected - covered by collapsible sections imo ~~may not be relevant when collapsible is implemented?~~
- [x] Improvements to text feedback - as per #92 
- [x] Graphs listed in collapsible sections - as per #115

**Comment by olaven** [comment]
Closing, as every checkpoint has been addressed 🎉
