### ISSUE TITLE
Calculate server-side 

### ISSUE THREAD

**Issue by olaven** [olaven/krets#94]
The code in `Charts.tsx` is based on client side calculations of all available responses. 
This scales very badly. As a solution, endpoints calculating this data using SQL-queries 
(i.e. keep calculations as far down the stack as possible) should be implemented. 

- [x] Line Chart - as per #162 
- [x] Bar Chart - as per #162 
- [x] Overall average - as per #99

**Comment by olaven** [comment]
I think this may be the most important focus of the milestone. 
I am pinning it as the main thing to focus on in the time left in the Test Ready-milestone.
